const { PrismaClient } = require('@prisma/client');
const p = new PrismaClient();

const translations = [
  {id:"fe121b3c-9a41-4f0a-a414-70e8749a8980",q:"Un technicien est chargé de signer une mainlevée de maintenance pour un composant qui a été réparé mais pas inspecté par un technicien indépendant. Quelle est l'action la PLUS appropriée du technicien ?",e:"Selon la RAC 571.10, une inspection indépendante est obligatoire avant de signer une mainlevée de maintenance. Signer sans celle-ci violerait les exigences réglementaires et pourrait compromettre la sécurité du vol.",o:["Signer la mainlevée de maintenance et noter que l'inspection indépendante n'a pas été effectuée.","Refuser de signer la mainlevée de maintenance jusqu'à ce que l'inspection indépendante soit effectuée.","Contacter le technicien indépendant pour confirmer la réparation avant de signer.","Procéder à la signature de la mainlevée puisque la réparation répond aux directives du fabricant."]},
  {id:"f68d09c5-cf35-45af-8047-6885889520a4",q:"Lors d'une inspection, un technicien constate qu'un mécanisme de verrouillage sur un composant du train d'atterrissage est défectueux. Quelle est l'action la PLUS appropriée pour le technicien ?",e:"Les composants critiques pour la sécurité, comme les mécanismes de verrouillage du train d'atterrissage, doivent répondre à des normes opérationnelles strictes. Selon la RAC 571, tout défaut doit être traité immédiatement.",o:["Lubrifier le mécanisme et l'inspecter à nouveau plus tard.","Remplacer le mécanisme de verrouillage selon les normes de maintenance.","Documenter la constatation et permettre à l'avion de fonctionner jusqu'à la prochaine maintenance programmée.","Désactiver temporairement le mécanisme de verrouillage jusqu'à ce que les réparations puissent être effectuées."]},
  {id:"eeff54bb-7815-4137-9224-f0908096ab17",q:"Suite à une procédure de maintenance, un technicien omet de documenter le remplacement d'une pièce dans les dossiers techniques de l'avion. Quelle pourrait être la conséquence la PLUS significative de cet oubli ?",e:"L'omission de documenter les remplacements de pièces peut entraîner des problèmes de sécurité importants selon la RAC 605.86.",o:["Le technicien pourrait faire face à des mesures disciplinaires de la part de l'OMA.","L'avion pourrait être considéré comme non navigable lors de la prochaine inspection.","La pièce pourrait ne pas être admissible à une garantie.","L'OMA pourrait recevoir une amende lors des procédures d'audit."]},
  {id:"20f1e664-46ee-41de-adc7-688be9f013a3",q:"Un technicien nouvellement qualifié n'est pas sûr des procédures de manipulation des pièces à durée de vie limitée lors de la maintenance. Quelle est la MEILLEURE ressource à consulter ?",e:"Le manuel de maintenance du fabricant contient les procédures et limitations spécifiques pour les pièces à durée de vie limitée, comme l'exigent la RAC 571 et la Norme 566.",o:["Le manuel de maintenance du fabricant pour l'aéronef spécifique.","Le site Web de Transports Canada pour les dernières réglementations.","Le manuel des politiques et procédures internes de l'OMA.","L'AC 43.13 pour les pratiques de maintenance générales."]},
  {id:"c4426c6a-5fa9-4df3-a9bb-fedd7fd76e21",q:"Un OMA n'a pas respecté une consigne de navigabilité (CN) dans les délais impartis. Quelle est la conséquence la PLUS grave ?",e:"Le non-respect d'une CN peut entraîner la suspension des certificats d'exploitation, comme l'exige la RAC 573.10.",o:["Un avertissement de Transports Canada sans autre action.","La suspension du certificat d'exploitation de l'OMA jusqu'à ce que la conformité soit atteinte.","Une amende qui sera imposée à l'OMA.","Une surveillance accrue lors des audits futurs sans pénalités immédiates."]},
  {id:"2b52b754-fc9c-4e8d-8bbe-81cec06408dc",q:"Lors d'une inspection pré-vol, un technicien remarque que le couple sur un boulon critique semble inférieur à la spécification. Que doit faire le technicien en PREMIER ?",e:"Le technicien ne doit pas prendre de mesures non autorisées. Signaler l'observation garantit que le problème est évalué selon la RAC 571.10.",o:["Re-sererrer le boulon immédiatement avant le vol.","Documenter l'observation et informer le superviseur de maintenance.","Procéder au vol car le boulon est toujours fixé.","Vérifier les dossiers de maintenance de l'avion pour les valeurs de couple précédentes."]},
  {id:"d5f27a55-d3f2-4b53-a0b2-62b093b81e04",q:"Après l'émission d'un bulletin de service obligatoire pour un modèle d'avion, quelle est la MEILLEURE marche à suivre pour un OMA ?",e:"Les bulletins de service obligatoires doivent être respectés immédiatement. La RAC 573.03 exige que les actions de maintenance soient documentées.",o:["Évaluer le bulletin de service et décider si une action est nécessaire.","Documenter le bulletin mais ne prendre aucune action immédiate.","Mettre en œuvre les actions requises et mettre à jour les dossiers de maintenance.","Attendre la prochaine maintenance programmée pour traiter le bulletin."]},
  {id:"2e7f033b-728d-4f02-9239-37430a3b4b44",q:"Un technicien rencontre une conduite de carburant corrodée lors d'une inspection. Quelle est l'action la PLUS appropriée ?",e:"Les conduites de carburant corrodées doivent être remplacées selon la RAC 571. Les réparations temporaires ne sont pas acceptables.",o:["Nettoyer la zone et appliquer un inhibiteur de corrosion.","Remplacer la conduite de carburant selon le manuel du fabricant.","Documenter la constatation et continuer l'inspection.","Effectuer une réparation temporaire et surveiller jusqu'à la prochaine inspection."]},
  {id:"3e5552b2-8e5c-4d25-a562-7716c2a9f2fb",q:"Lors d'une inspection programmée, un technicien identifie qu'une pièce à durée de vie limitée a dépassé sa durée de vie maximale. Quelle est l'action la PLUS appropriée ?",e:"Selon la RAC 571.10, les pièces à durée de vie limitée doivent être remplacées dès qu'elles atteignent leur durée de vie maximale.",o:["Continuer à utiliser la pièce jusqu'à ce qu'elle cesse de fonctionner.","Remplacer la pièce par une neuve et documenter l'action.","Effectuer une inspection détaillée avant de décider du remplacement.","Déposer un rapport auprès de Transports Canada avant d'agir."]},
  {id:"89d6b357-aa34-44e6-b170-b4e38f7461db",q:"Lors d'une inspection, un technicien trouve des signes de corrosion sur un composant en aluminium. Quelle est la MEILLEURE action ?",e:"Selon l'AC 43.13, toute corrosion doit être évaluée et traitée conformément aux données de maintenance approuvées.",o:["Ignorer la corrosion car elle est mineure.","Nettoyer la zone et appliquer un revêtement protecteur.","Signaler la constatation et consulter le manuel de réparation.","Remplacer immédiatement le composant sans évaluation supplémentaire."]},
  {id:"5b255d9d-9741-4b95-8cf0-0592bf5bda1f",q:"Lors d'une inspection pré-vol, un technicien remarque que le journal de bord est incomplet. Quelle est la meilleure marche à suivre ?",e:"Selon la RAC 605.86, le journal de bord doit refléter fidèlement toute la maintenance effectuée.",o:["Procéder au vol tant que l'avion semble navigable.","Informer le pilote et documenter l'observation dans le journal de bord.","Remplir les inscriptions manquantes soi-même pour éviter les retards.","Contacter le responsable de maintenance pour des instructions."]},
  {id:"25d82477-9d38-4665-905c-2c4c771dd277",q:"Un technicien découvre un composant non fonctionnel, mais le manuel ne fournit pas de procédure de réparation spécifique. Que doit faire le technicien ?",e:"Selon la RAC 571.10, s'il n'existe pas de procédure approuvée, le technicien doit recommander le remplacement.",o:["Tenter une réparation temporaire.","Consulter un technicien supérieur.","Documenter l'état et recommander le remplacement.","Déposer un rapport auprès de Transports Canada."]},
  {id:"2e01e517-e7a4-4647-b4cc-292ef505358a",q:"Après une tâche de maintenance, un technicien doit signer la mainlevée. Quelles informations doivent être incluses ?",e:"Selon la RAC 573.04, la mainlevée doit inclure le nom du technicien et la date.",o:["Le nom complet du technicien et la date de la mainlevée.","Le nom du technicien précédent.","Un résumé de l'historique de l'avion.","Une liste de contrôle de toutes les tâches effectuées."]},
  {id:"be393ea8-e5d0-4c7e-8826-a8349c6c4713",q:"Un technicien ne sait pas comment exécuter une réparation spécifique. Quelle est la marche à suivre la plus appropriée ?",e:"Consulter le manuel de maintenance du fabricant est essentiel, conformément à la RAC 573.10.",o:["Tenter la réparation avec des connaissances générales.","Contacter un technicien plus expérimenté.","Se référer au manuel de maintenance du fabricant.","Reporter la réparation jusqu'à plus d'informations."]},
  {id:"b5f65a41-671d-41c4-b439-51ea28fe6578",q:"Lors d'une inspection, un technicien découvre qu'une CN n'a pas été respectée. Quelle action entreprendre ?",e:"La RAC 571.01 exige que toutes les CN soient respectées avant qu'un aéronef soit considéré navigable.",o:["Documenter et continuer l'inspection.","Informer le responsable et assurer la conformité avant de poursuivre.","Ignorer la CN si l'avion semble sûr.","Terminer l'inspection et recommander la conformité au prochain cycle."]},
  {id:"aac4a47b-93b0-4ae2-91aa-ab0917f84f1e",q:"Un technicien termine une réparation et prépare la documentation. Que doit-elle inclure ?",e:"La RAC 573.04 exige une description du travail et la signature du technicien.",o:["Une description de la réparation et le nom du technicien.","Les calculs de poids et d'équilibre.","Le coût total de la réparation.","Les coordonnées personnelles du technicien."]},
  {id:"05aa8380-51e2-439b-83ff-e9057796e151",q:"Un technicien prépare une mainlevée après une réparation importante. Quelle action est REQUISE avant de signer ?",e:"Selon la RAC 573.03, une inspection indépendante est requise.",o:["L'approbation du propriétaire de l'avion.","Une inspection indépendante par un autre technicien.","Une inscription dans le journal de bord.","Un examen du calendrier de maintenance."]},
  {id:"c267435a-01ba-4637-868c-b652f1428b72",q:"Lors d'un contrôle, un technicien trouve une modification non approuvée du système de carburant. PREMIÈRE action ?",e:"Le technicien doit informer la direction de l'OMA selon la RAC 573.04.",o:["Documenter et continuer le contrôle.","Informer la direction et retirer la modification non approuvée.","Ignorer la modification si elle n'affecte pas le fonctionnement.","Procéder à la mainlevée après une inspection visuelle."]},
  {id:"1967df0a-0e93-4423-8f9b-66e782304172",q:"Un technicien s'apprête à faire la maintenance d'un avion avec historique de problèmes hydrauliques. PREMIÈRE étape ?",e:"Comprendre l'historique des problèmes est crucial pour planifier la maintenance selon la RAC 571.",o:["Vérifier les niveaux de liquide hydraulique.","Examiner l'historique de maintenance.","Préparer les outils nécessaires.","Effectuer un test fonctionnel du système hydraulique."]},
  {id:"41edc2ed-7fb9-4d1e-870d-1c50fab91836",q:"Un technicien remarque qu'une CN n'a pas été respectée. Quelle est son obligation ?",e:"La RAC 571.01 souligne que le respect des CN est obligatoire.",o:["Ignorer la CN si plus d'un mois s'est écoulé.","Mettre l'avion au sol jusqu'à vérification de conformité.","Documenter l'oubli et procéder à la maintenance.","Contacter l'autorité réglementaire."]},
  {id:"be1826f7-1fc5-4010-8ff3-e86fb89af844",q:"Un technicien découvre un couple incorrect sur un composant critique après maintenance. Procédure correcte ?",e:"La RAC 571.10 exige que toute maintenance réponde aux spécifications du fabricant.",o:["Documenter et attendre la prochaine maintenance.","Re-sererrer à la spécification correcte et documenter.","Laisser le composant tel quel.","Informer le pilote."]},
  {id:"b88f8a41-4e76-4fdd-935c-95d19572f58d",q:"Lors d'une inspection, une pièce à durée de vie limitée approche de sa limite. MEILLEURE action ?",e:"La RAC 571.10 exige le remplacement à ou avant la durée de vie maximale.",o:["Continuer à utiliser jusqu'à défaillance.","Remplacer immédiatement.","Surveiller et documenter l'utilisation.","Planifier le remplacement avant la limite."]},
  {id:"9efceb7f-6546-4d09-98fe-f1d4f87318e6",q:"Un technicien effectue une mainlevée après une inspection programmée. Exigence clé avant de signer ?",e:"Selon la Norme 573, une inspection indépendante est nécessaire.",o:["L'inspection sans aucune constatation.","Une inspection indépendante effectuée et documentée.","L'avion doit avoir volé après la maintenance.","Le technicien doit être certifié depuis au moins un an."]},
  {id:"5ca1b3fc-6b9d-46a1-a0cd-63fc871ab410",q:"Après une réparation majeure, quelle documentation est requise pour la conformité aux RAC ?",e:"Selon la RAC 571.10, toutes les réparations majeures doivent être documentées.",o:["Une confirmation verbale à la direction.","Un rapport détaillé incluant procédures et pièces.","Une mainlevée signée par tout technicien.","Un résumé dans le journal de bord uniquement."]},
  {id:"b3bbde92-1aff-4801-af6a-b0e39e6941c2",q:"Après une tâche de maintenance, info MINIMALE à documenter ?",e:"La RAC 571.10 exige une mainlevée avec description détaillée du travail.",o:["Le nom du technicien et la date.","Seulement la description de la tâche.","Le temps et les matériaux utilisés.","Une mainlevée signée et une description détaillée."]},
  {id:"8655c0d9-fe1a-476f-9be5-dd60a86beec3",q:"Signes de corrosion sur un composant critique. PREMIÈRE action ?",e:"Selon l'AC 43.13, la corrosion doit être évaluée avant d'agir.",o:["Ignorer si mineure.","Documenter et continuer l'inspection.","Retirer immédiatement le composant.","Informer le superviseur et évaluer l'étendue."]},
  {id:"9cfce5fd-46d6-416c-b95e-76d4a4fe428c",q:"Un technicien n'est pas sûr qu'une méthode de réparation soit approuvée. Que faire ?",e:"La Norme 566 exige d'utiliser des méthodes approuvées du manuel de maintenance.",o:["Utiliser la méthode si elle semble efficace.","Consulter le manuel de maintenance.","Demander l'avis d'un collègue.","Procéder si le composant est fonctionnel."]},
  {id:"ef4968c3-9dd5-4902-ac64-991632017e30",q:"Journal de bord sans inscriptions des deux derniers vols. Action appropriée ?",e:"Selon la RAC 605.92, le journal doit être tenu avec précision.",o:["Continuer le vol prévu.","Mettre l'avion au sol jusqu'à complétion.","Remplir de mémoire.","Informer le superviseur et documenter."]},
  {id:"c333267a-a95e-4083-8a0a-72ad734b60c9",q:"Après maintenance du système électrique, étape la PLUS importante avant remise en service ?",e:"Compléter la documentation de mainlevée est requis par la RAC 571 et la Norme 573.",o:["Inspection visuelle approfondie.","Compléter la documentation de mainlevée.","Tester tous les systèmes électriques.","Examiner le manuel de maintenance."]},
  {id:"9e82e39f-5035-49af-9ae9-91459835d34d",q:"Panneau audio sans alimentation. PREMIÈRE étape de dépannage ?",e:"Vérifier les fusibles est fondamental selon l'AC 43.13.",o:["Vérifier les fusibles du panneau audio.","Inspecter le câblage.","Tester le panneau audio.","Vérifier l'interrupteur principal."]},
  {id:"c4c9f53a-3e19-46b8-9096-2eb982fd9316",q:"CN relative au système électrique non respectée. Responsabilité immédiate du technicien ?",e:"Le respect des CN est obligatoire. Le technicien doit signaler à son superviseur.",o:["Informer le superviseur et assurer la conformité avant le prochain vol.","Documenter le non-respect dans le journal.","Continuer la maintenance programmée.","Effectuer une évaluation des risques."]},
  {id:"0073c38d-ebdb-4ab6-a5cb-ed7b99af210a",q:"Tension à un connecteur significativement inférieure à la spécification. Que faire ?",e:"Inspecter le connecteur pour corrosion ou mauvaises connexions, selon l'AC 43.13.",o:["Remplacer le composant connecté.","Inspecter le connecteur pour corrosion ou dommages.","Documenter dans le journal de maintenance.","Consulter le schéma de câblage."]},
  {id:"7d7911d1-899e-4e58-9455-63d952ee820d",q:"Après remplacement d'une batterie, quel composant vérifier pour éviter les courts-circuits ?",e:"Les bornes doivent être propres et serrées selon l'AC 43.13.",o:["S'assurer que les bornes sont propres et serrées.","Fixer le couvercle avec du frein-fil.","Vérifier la tension avant installation.","Étiqueter avec la date d'installation."]},
  {id:"7ceda994-73dd-46bb-92cb-c57a622a5aae",q:"Faisceau de câbles qui frotte contre un bord métallique. Action corrective ?",e:"Réacheminer le faisceau élimine le risque de courts-circuits selon la RAC 571.",o:["Appliquer du ruban électrique.","Réacheminer le faisceau.","Documenter et surveiller.","Remplacer tout le faisceau."]},
  {id:"31273175-9132-4244-a3a9-7d1c14bc1c86",q:"Contrôle fonctionnel des instruments du cockpit. Contrôle le PLUS critique ?",e:"Confirmer l'affichage de données précises est essentiel selon la RAC 571.",o:["Vérifier la continuité du câblage.","S'assurer que les lumières s'allument.","Confirmer l'affichage de données précises.","Vérifier les dommages physiques."]},
  {id:"4f9e94d6-2a3b-47d6-8eab-1269d6ca1f9a",q:"Inspection du système électrique pour corrosion. Zone à prioriser ?",e:"Connecteurs et bornes exposés à l'humidité sont prioritaires selon l'AC 43.13.",o:["Connecteurs et bornes exposés à l'humidité.","Disjoncteurs et fusibles.","Isolation du câblage.","Compartiments de batterie."]},
  {id:"ff5f9dde-4ceb-4f37-ad8c-1f8610e0248d",q:"Pilote automatique se déconnecte par intermittence. PREMIÈRE étape ?",e:"Inspecter le câblage et les connecteurs d'abord selon l'AC 43.13.",o:["Vérifier les servos et gouvernes.","Examiner les dossiers de maintenance.","Inspecter le câblage et connecteurs.","Effectuer un essai au sol."]},
  {id:"4f200643-5d3c-4e3f-87af-979aacd0dddc",q:"Feux de navigation ne fonctionnent pas. PREMIÈRE action ?",e:"Vérifier le disjoncteur et le câblage selon l'AC 43.13.",o:["Remplacer les ampoules.","Vérifier le disjoncteur et le câblage.","Inspecter les lentilles.","Documenter le défaut."]},
  {id:"5315a80a-9d9a-4b5f-b43e-7cd7f50d9eb7",q:"Divergence dans le schéma de câblage. Action appropriée ?",e:"Contacter le fabricant pour clarification selon la RAC 573.",o:["Utiliser le schéma comme guide.","Contacter le fabricant.","Procéder selon l'expérience personnelle.","Ignorer la divergence."]},
  {id:"f87b24b6-f39b-4e5f-a4a4-46797576caf4",q:"Après installation de nouvelles avioniques, que doit inclure le contrôle fonctionnel ?",e:"Un contrôle complet sous diverses conditions est requis par la Norme 566.",o:["Tester sous diverses conditions opérationnelles.","Vérifier uniquement la mise sous tension.","Documenter sans autres vérifications.","Limiter aux systèmes précédemment défectueux."]},
  {id:"c7ddecf8-2ee0-4e43-9ed3-856ae233ec21",q:"Lumières scintillent au démarrage du moteur. PREMIÈRE vérification ?",e:"Cela indique une chute de tension. Vérifier la batterie selon l'AC 43.13.",o:["Inspecter la tension de la batterie.","Vérifier l'alternateur.","Vérifier les disjoncteurs.","Chercher des connexions desserrées."]},
  {id:"92b266fc-1e7a-455e-9125-57a37e0bcfd8",q:"Connexion à la terre desserrée sur l'ECU. MEILLEURE action immédiate ?",e:"Resserrer et documenter dans le journal de bord selon la RAC 605.",o:["Resserrer et documenter dans le journal.","Remplacer l'ECU.","Ignorer car non critique.","Informer le pilote."]},
  {id:"a6c0494a-7797-49e2-a478-3f5e4e87e6ad",q:"Pilote automatique se déconnecte par intermittence. Action initiale appropriée ?",e:"Inspecter d'abord le câblage selon l'AC 43.13.",o:["Inspecter le câblage de commande.","Calibrer le système.","Mettre à jour le logiciel.","Remplacer le contrôleur."]},
  {id:"f95bb88e-ca12-4ba1-871c-d09526da4438",q:"Système de navigation fournit des lectures inexactes. Étape critique avant diagnostic ?",e:"Vérifier l'étalonnage selon les spécifications du fabricant.",o:["Vérifier le poids et équilibre.","S'assurer du bon étalonnage.","Inspecter l'antenne GPS.","Vérifier la version logicielle."]},
  {id:"325ef323-4d7f-4997-9ff9-3c96974274f7",q:"Câblage électrique effiloché à plusieurs endroits. Action appropriée ?",e:"Le câblage endommagé doit être remplacé selon la Norme 571.",o:["Envelopper avec du ruban électrique.","Remplacer le câblage endommagé.","Signaler et continuer l'exploitation.","Isoler et laisser tel quel."]},
  {id:"2e78fc81-a4d1-43a6-b77b-c33ddc7b6d83",q:"Corrosion sur une borne de batterie. MEILLEURE action ?",e:"Nettoyer et appliquer un revêtement protecteur selon l'AC 43.13.",o:["Nettoyer et appliquer un revêtement protecteur.","Remplacer la batterie.","Signaler sans autre action.","Ignorer."]},
  {id:"2cbd94f5-ddcb-44b0-b26d-b5821bc58c4e",q:"Après remplacement d'un transpondeur, quelle réglementation pour la certification ?",e:"Tester la conformité aux données de maintenance approuvées selon la RAC 571.",o:["Tester pour la conformité aux données approuvées.","Remplacer uniquement par un modèle identique.","Indiquer le numéro de série dans le journal.","Documenter dans la mainlevée uniquement."]},
  {id:"08038613-20c8-4c61-9cfd-c01b02a55451",q:"PFD ne reçoit pas d'alimentation. PREMIÈRE étape de dépannage ?",e:"Vérifier le disjoncteur selon l'AC 43.13.",o:["Vérifier le disjoncteur du PFD.","Inspecter le faisceau de câbles.","Remplacer le PFD.","Examiner les journaux de maintenance."]},
  {id:"e352f239-bbf4-4729-92d7-93ef880b4874",q:"PFD affiche des lectures d'altitude incorrectes. Après vérification statique/pitot, prochaine étape ?",e:"Vérifier les connexions électriques selon la RAC 571.",o:["Remplacer immédiatement le PFD.","Vérifier les connexions électriques et le câblage.","Calibrer l'altimètre.","Consulter le manuel de maintenance."]},
  {id:"84a02336-70b1-4325-990e-c08ddbfa97fa",q:"Disjoncteur grillé dans le système électrique. Action avant remplacement ?",e:"Enquêter sur la cause de la défaillance selon la RAC 573.",o:["Remplacer et continuer l'inspection.","Enquêter sur la cause et documenter.","Réinitialiser et surveiller.","Consulter le schéma de câblage."]},
];

async function main() {
  let count = 0;
  for (const t of translations) {
    await p.question.update({
      where: { id: t.id },
      data: { question_fr: t.q, explanation_fr: t.e, options_fr: JSON.stringify(t.o) }
    });
    count++;
  }
  console.log(`✅ ${count} questions traduites`);
  await p.$disconnect();
}

main().catch(e => { console.error(e); p.$disconnect(); });
